"""Initial migration
Revision ID: 2024_01_01_000000_initial_migration
Revises: 
Create Date: 2024-01-01 00:00:00.000000
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision = '2024_01_01_000000_initial_migration'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Таблица users
    op.create_table('users',
                    sa.Column('id', sa.BigInteger(),
                              nullable=False, autoincrement=True),
                    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
                    sa.Column('trial_messages_left', sa.Integer(),
                              server_default='10', nullable=False),
                    sa.Column('is_vip', sa.Boolean(),
                              server_default='false', nullable=False),
                    sa.Column('last_active', sa.TIMESTAMP(
                        timezone=True), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('telegram_id')
                    )
    op.create_index('idx_users_telegram_id', 'users',
                    ['telegram_id'], unique=False)

    # Таблица active_users
    op.create_table('active_users',
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('user_id')
                    )

    # Таблица message_history
    op.create_table('message_history',
                    sa.Column('id', sa.BigInteger(),
                              nullable=False, autoincrement=True),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('ai_provider', postgresql.ENUM('chatgpt', 'perplexity',
                                                             'deepseek', name='ai_provider_type', create_type=False), nullable=False),
                    sa.Column('ai_model', sa.String(
                        length=100), nullable=False),
                    sa.Column('user_message', sa.Text(), nullable=False),
                    sa.Column('ai_response', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('idx_message_history_user_id',
                    'message_history', ['user_id'], unique=False)
    op.create_index('idx_message_history_created_at',
                    'message_history', ['created_at'], unique=False)

    # Таблица subscriptions
    op.create_table('subscriptions',
                    sa.Column('id', sa.BigInteger(),
                              nullable=False, autoincrement=True),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('plan', postgresql.ENUM('trial', 'premium',
                                                      name='subscription_plan_type', create_type=False), nullable=False),
                    sa.Column('start_date', sa.Date(), nullable=False),
                    sa.Column('end_date', sa.Date(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('idx_subscriptions_user_id',
                    'subscriptions', ['user_id'], unique=False)
    op.create_index('idx_subscriptions_end_date',
                    'subscriptions', ['end_date'], unique=False)

    # Таблица payments
    op.create_table('payments',
                    sa.Column('id', sa.BigInteger(),
                              nullable=False, autoincrement=True),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('amount', sa.Numeric(
                        precision=10, scale=2), nullable=False),
                    sa.Column('currency', postgresql.ENUM('RUB', 'USD', 'EUR',
                                                          name='currency_code', create_type=False), nullable=False),
                    sa.Column('payment_date', sa.Date(), nullable=False),
                    sa.Column('success', sa.Boolean(), nullable=False),
                    sa.Column('telegram_payment_id', sa.String(
                        length=255), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('idx_payments_user_id', 'payments',
                    ['user_id'], unique=False)
    op.create_index('idx_payments_payment_date', 'payments',
                    ['payment_date'], unique=False)
    op.create_index('idx_payments_success', 'payments',
                    ['success'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payments_success', table_name='payments')
    op.drop_index('idx_payments_payment_date', table_name='payments')
    op.drop_index('idx_payments_user_id', table_name='payments')
    op.drop_table('payments')

    op.drop_index('idx_subscriptions_end_date', table_name='subscriptions')
    op.drop_index('idx_subscriptions_user_id', table_name='subscriptions')
    op.drop_table('subscriptions')

    op.drop_index('idx_message_history_created_at',
                  table_name='message_history')
    op.drop_index('idx_message_history_user_id', table_name='message_history')
    op.drop_table('message_history')

    op.drop_table('active_users')

    op.drop_index('idx_users_telegram_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
